# Generated by Django 3.2.8 on 2021-11-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('Districk', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=False)),
                ('Datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='karmaapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='karmaapp.user')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karmaapp.product')),
                ('billing_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karmaapp.billing_address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karmaapp.user')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karmaapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karmaapp.user')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.AddField(
            model_name='billing_address',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='karmaapp.user'),
        ),
    ]
